name: publish Package

on:
  push:
    branches:
      - master
  create:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  release-new-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # variables: https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables
      - run: git config --global user.name "$GITHUB_ACTOR"
      - run: git config --global user.email "andreformento.sc@gmail.com"
      - run: npm version patch
      - run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
